export const productos = [
  {
    id: "piedra-blanca",
    codigo: "PIEDRA-BLANCA",
    nombre: "Piedra blanca",
    familia: "Piedras",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 1900,
    comision: { tipo: "fija", valor: 700 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 5900 },
      { desde: 10, precioUnitario: 5500 },
      { desde: 20, precioUnitario: 5100 },
    ],
    aliases: ["piedra blanca", "piedras blancas", "blanca", "blancas", "bolsas blancas"],
    activo: true,
  },
  {
    id: "piedra-gris-claro",
    codigo: "PIEDRA-GRIS-CLARO",
    nombre: "Piedra gris claro",
    familia: "Piedras",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 950,
    comision: { tipo: "fija", valor: 600 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 4800 },
      { desde: 10, precioUnitario: 4400 },
      { desde: 20, precioUnitario: 3900 },
    ],
    aliases: ["piedra gris claro", "gris claro", "grises claras", "piedras gris claro"],
    activo: true,
  },
  {
    id: "piedra-gris-oscuro",
    codigo: "PIEDRA-GRIS-OSCURO",
    nombre: "Piedra gris oscuro",
    familia: "Piedras",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 1650,
    comision: { tipo: "fija", valor: 600 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 5200 },
      { desde: 10, precioUnitario: 4800 },
      { desde: 20, precioUnitario: 4400 },
    ],
    aliases: ["piedra gris oscuro", "gris oscuro", "grises oscuras", "piedras gris oscuro"],
    activo: true,
  },
  {
    id: "arena-gruesa",
    codigo: "ARENA-GRUESA",
    nombre: "Arena gruesa",
    familia: "Áridos",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 660,
    comision: { tipo: "fija", valor: 300 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 3599 },
      { desde: 10, precioUnitario: 3199 },
      { desde: 20, precioUnitario: 2999 },
    ],
    aliases: ["arena gruesa", "arena comun", "arena común", "gruesa"],
    activo: true,
  },
  {
    id: "arena-fina-parana",
    codigo: "ARENA-FINA-PARANA",
    nombre: "Arena fina Paraná",
    familia: "Áridos",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 1050,
    comision: { tipo: "fija", valor: 700 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 3999 },
      { desde: 10, precioUnitario: 3599 },
      { desde: 20, precioUnitario: 3299 },
    ],
    aliases: ["arena fina", "arena fina parana", "arena fina paraná", "fina parana", "fina paraná", "parana", "paraná"],
    activo: true,
  },
  {
    id: "tierra-negra",
    codigo: "TIERRA-NEGRA",
    nombre: "Tierra negra",
    familia: "Áridos",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 750,
    comision: { tipo: "fija", valor: 400 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 4200 },
      { desde: 10, precioUnitario: 3800 },
      { desde: 20, precioUnitario: 3500 },
    ],
    aliases: ["tierra", "tierra negra"],
    activo: true,
  },
  {
    id: "triturado-4-6",
    codigo: "TRITURADO-4-6",
    nombre: "Triturado 4-6",
    familia: "Triturados",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 950,
    comision: { tipo: "fija", valor: 600 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 4399 },
      { desde: 10, precioUnitario: 3999 },
      { desde: 20, precioUnitario: 3699 },
    ],
    aliases: ["triturado 4-6", "4-6", "4 6"],
    activo: true,
  },
  {
    id: "base-0-20",
    codigo: "BASE-0-20",
    nombre: "0-20 Base",
    familia: "Áridos",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 0,
    comision: { tipo: "sin_comision", valor: 0 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 3799 },
      { desde: 10, precioUnitario: 3399 },
      { desde: 20, precioUnitario: 3099 },
    ],
    aliases: ["0-20", "0 20", "base", "base 0-20"],
    activo: true,
    requiereRevision: true,
  },
  {
    id: "triturado-10-30",
    codigo: "TRITURADO-10-30",
    nombre: "Triturado 10-30",
    familia: "Triturados",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 0,
    comision: { tipo: "sin_comision", valor: 0 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 4399 },
      { desde: 10, precioUnitario: 3999 },
      { desde: 20, precioUnitario: 3599 },
    ],
    aliases: ["triturado 10-30", "10-30", "10 30"],
    activo: true,
    requiereRevision: true,
  },
  {
    id: "triturado-30-50",
    codigo: "TRITURADO-30-50",
    nombre: "Triturado 30-50",
    familia: "Triturados",
    unidad: "bolsa 20 kg",
    costoMaterialUnitario: 0,
    comision: { tipo: "sin_comision", valor: 0 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [
      { desde: 1, precioUnitario: 4399 },
      { desde: 10, precioUnitario: 3999 },
      { desde: 20, precioUnitario: 3599 },
    ],
    aliases: ["triturado 30-50", "30-50", "30 50"],
    activo: true,
    requiereRevision: true,
  },
  {
    id: "compost",
    codigo: "COMPOST",
    nombre: "Compost",
    familia: "Áridos",
    unidad: "bolsa",
    costoMaterialUnitario: 4500,
    comision: { tipo: "fija", valor: 900 },
    descuentoEfectivo: { aplica: false, porcentaje: 0 },
    precios: [{ desde: 1, precioUnitario: 0 }],
    aliases: ["compost"],
    activo: true,
    requiereRevision: true,
  },
  {
    id: "barral-2205",
    codigo: "2205",
    nombre: "Barral madera 22 mm x 1,40 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 4521.6,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 10700 }],
    aliases: ["barral 22mm 1.40", "barral 22 mm 1,40", "barral de 1.4 de 22mm", "barral 1,40 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2206",
    codigo: "2206",
    nombre: "Barral madera 22 mm x 1,60 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 4844,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 11700 }],
    aliases: ["barral 22mm 1.60", "barral 22 mm 1,60", "barral de 1.6 de 22mm", "barral 1,60 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2207",
    codigo: "2207",
    nombre: "Barral madera 22 mm x 1,80 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 5731.2,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 12700 }],
    aliases: ["barral 22mm 1.80", "barral 22 mm 1,80", "barral de 1.8 de 22mm", "barral 1,80 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2208",
    codigo: "2208",
    nombre: "Barral madera 22 mm x 2,00 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 5852,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 13500 }],
    aliases: ["barral 22mm 2.00", "barral 22 mm 2,00", "barral de 2 de 22mm", "barral 2,00 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2209",
    codigo: "2209",
    nombre: "Barral madera 22 mm x 2,20 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 6046.4,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 14700 }],
    aliases: ["barral 22mm 2.20", "barral 22 mm 2,20", "barral de 2.2 de 22mm", "barral 2,20 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2210",
    codigo: "2210",
    nombre: "Barral madera 22 mm x 2,40 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 6432.8,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 15500 }],
    aliases: ["barral 22mm 2.40", "barral 22 mm 2,40", "barral de 2.4 de 22mm", "barral 2,40 m de 22 mm"],
    activo: true,
  },
  {
    id: "barral-2211",
    codigo: "2211",
    nombre: "Barral madera 32 mm x 1,40 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 9698.4,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 20000 }],
    aliases: ["barral 32mm 1.40", "barral 32 mm 1,40", "barral de 1.4 de 32mm", "barral 1,40 m de 32 mm"],
    activo: true,
  },
  {
    id: "barral-2214",
    codigo: "2214",
    nombre: "Barral madera 32 mm x 2,00 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 16520,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 26000 }],
    aliases: ["barral 32mm 2.00", "barral 32 mm 2,00", "barral de 2 de 32mm", "barral 2,00 m de 32 mm"],
    activo: true,
  },
  {
    id: "barral-2215",
    codigo: "2215",
    nombre: "Barral madera 32 mm x 2,20 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 18134.4,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 34000 }],
    aliases: ["barral 32mm 2.20", "barral 32 mm 2,20", "barral de 2.2 de 32mm", "barral 2,20 m de 32 mm"],
    activo: true,
  },
  {
    id: "barral-2212",
    codigo: "2212",
    nombre: "Barral madera 34 mm x 1,60 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 10904,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 22000 }],
    aliases: ["barral 34mm 1.60", "barral 34 mm 1,60", "barral de 1.6 de 34mm", "barral 1,60 m de 34 mm"],
    activo: true,
  },
  {
    id: "barral-2213",
    codigo: "2213",
    nombre: "Barral madera 34 mm x 1,80 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 12265.6,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 24000 }],
    aliases: ["barral 34mm 1.80", "barral 34 mm 1,80", "barral de 1.8 de 34mm", "barral 1,80 m de 34 mm"],
    activo: true,
  },
  {
    id: "barral-2216",
    codigo: "2216",
    nombre: "Barral madera 34 mm x 2,40 m",
    familia: "Barrales madera",
    unidad: "unidad",
    costoMaterialUnitario: 16232,
    comision: { tipo: "porcentaje", valor: 12 },
    descuentoEfectivo: { aplica: true, porcentaje: 10 },
    precios: [{ desde: 1, precioUnitario: 38000 }],
    aliases: ["barral 34mm 2.40", "barral 34 mm 2,40", "barral de 2.4 de 34mm", "barral 2,40 m de 34 mm"],
    activo: true,
  },
];

export const vendedores = [
  { id: "vendedor-agus", nombre: "Agus", telefono: "", email: "", observaciones: "", activo: true },
  { id: "vendedor-rocio-facebook", nombre: "Rocío Facebook", telefono: "", email: "", observaciones: "Comisiones especiales si corresponde.", activo: true },
  { id: "vendedor-general", nombre: "General", telefono: "", email: "", observaciones: "", activo: true },
];
